---
# example playbook for running windows powershell script on target windows devices.

- name: run powershell
  hosts: '{{ target }}'
  tasks:
    - name: Run the powershell script 
      script: files/helloworld.ps1